name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        build_type: [Release]
        std: [11, 17]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --warn-uninitialized \
                -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -D CMAKE_CXX_STANDARD=${{matrix.std}} \
                -D UREACT_PEDANTIC:BOOL=y \
                -D UREACT_WERROR:BOOL=y \
                $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -j 10 -C ${{matrix.build_type}}  --output-on-failure
