name: "Windows"

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        label: [ "" ]
        os: [ windows-2022 ]
        build_type: [ Release ]
        architecture: [ x64 ]
        toolset_name: [ "", ClangCL ]
        std: [ 20 ]

        exclude:
          - toolset_name: ClangCL
            build_type: Debug

        include:
          - os: windows-2022
            cmake_generator: "Visual Studio 17 2022"

          - label: clang12
            os: windows-2019
            build_type: Release
            std: 17
            cxx: C:/Program Files/LLVM/bin/clang++.exe
            install: curl -fsSL -o LLVM12.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/LLVM-12.0.0-win64.exe ; 7z x LLVM12.exe -y -o"C:/Program Files/LLVM"
            cmake_generator: "MinGW Makefiles"

          - toolset_name: ClangCL
            build_type: Release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          ${{ matrix.install }}
          cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure
        if: ${{ contains(matrix.cmake_generator, 'Visual Studio') }}
        env:
          CXX: ${{ matrix.cxx }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          CMAKE_GENERATOR_TOOLSET: ${{ matrix.toolset_name }}
        run: cmake --warn-uninitialized
          -S .
          -B "${{ runner.workspace }}/build"
          -A "${{ matrix.architecture }}"
          -D CMAKE_CXX_STANDARD=${{ matrix.std }}
          -G "${{ matrix.cmake_generator }}"
          -D UREACT_PEDANTIC:BOOL=y
          -D UREACT_WERROR:BOOL=y

      - name: Configure
        if: ${{ !contains(matrix.cmake_generator, 'Visual Studio') }}
        env:
          CXX: ${{ matrix.cxx }}
          CXXFLAGS: ${{ matrix.cxxflags }}
        run: cmake --warn-uninitialized
          -S .
          -B "${{ runner.workspace }}/build"
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D CMAKE_CXX_STANDARD=${{ matrix.std }}
          -G "${{ matrix.cmake_generator }}"
          -D UREACT_PEDANTIC:BOOL=y
          -D UREACT_WERROR:BOOL=y

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel 10 --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: ctest -j 10 -C ${{ matrix.build_type }} --output-on-failure
